version: "3"
services:
  redis:
    container_name: redis
    image: redis
    restart: always

  superset:
    container_name: superset
    image: amancevice/superset
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      SUPERSET_HOME: /etc/superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset/conf/superset_config.py:/etc/superset/superset_config.py
      - superset:/var/lib/superset
volumes:
  superset:
